notas/urls.py
from django.urls import path
from notas import views

app_name='notas'

urlpatterns = [
    path('',views.listar_notas_user,name='listar_notas_user'),
    path('criar-nota/',views.create_nota,name='create_nota'),
    path('editar-nota/<int:pk>',views.update_nota,name='update_nota'),
    path('excluir-nota/<int:pk>',views.delete_nota,name='delete_nota')
]

project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('notas.urls'))
]

notas/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Nota(models.Model):
    titulo = models.CharField(max_length=200)
    conteudo = models.TextField()
    data_criacao = models.DateTimeField(auto_now_add=True)
    autor = models.ForeignKey(User,on_delete=models.PROTECT,verbose_name='Autor',related_name='notas')

    def __str__(self):
        return self.titulo

notas/forms.py
from django import forms
from .models import Nota

class NotaForm(forms.ModelForm):
    class Meta:
        model = Nota
        fields = ['titulo','conteudo']
        labels = {
            'titulo': 'Título',
            'conteudo': 'Conteúdo'
        }

notas/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.urls import reverse
from .models import Nota
from .forms import NotaForm
# Create your views here.


def listar_notas_user(request):
    notas = Nota.objects.filter(autor=request.user.pk)

    return render(request,'notas/notas_list_view.html',
            {
                'notas':notas,
                'form':NotaForm
            })

def create_nota(request):
    if request.method == 'POST':
        form = NotaForm(request.POST)
        
        if form.is_valid():
            nota = form.save(commit=False)
            nota.autor = request.user 
            nota.save()
            print(nota)

            return redirect(reverse('notas:listar_notas_user'))
    
    return redirect(reverse('notas:listar_notas_user'))

def update_nota(request,pk):
    nota = Nota.objects.filter(pk=pk).first()
    
    if request.method == 'POST':
        new_form = NotaForm(request.POST,instance=nota)
        if new_form.is_valid():
            new_form.save()
            
            return redirect(reverse('notas:listar_notas_user')) 
    else:
        form = NotaForm(instance=nota)

    return render(request,'notas/nota_update_view.html',{
        'form':form,
        'nota':nota
    })

def delete_nota(request,pk):
    nota = Nota.objects.filter(pk=pk).first()
    if request.method == 'POST':
        nota.delete()
        return redirect(reverse('notas:listar_notas_user'))
        
    return render(request,'notas/nota_delete_view.html',{'nota':nota})

notas/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <!--icon-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    
    <title>App Notas</title>

    <style>
        
        @import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap');

        body{
            background-color: #1A1A1A;
            font-family: "Montserrat", sans-serif;
        }

        header,h4{
            color:whitesmoke;
        }

        .card-notas{
            margin: auto;
            width: 600px;
            padding: 20px;
            border: 1px solid whitesmoke;
            border-radius:5px;
        }

        .card-nota{
            color:whitesmoke;
            border: 1px solid whitesmoke;
            border-radius:5px;
            padding: 20px;
            margin-bottom:10px;
            
        }

        .link-add-nota{
            display: inline-block;
            height: 40px; 
            line-height: 40px; 
            background-color: whitesmoke; 
            text-align: center; 
            padding: 0 10px;
            color:black;
            border-radius:5px;
            text-decoration: none;
            margin-bottom:5px;
        }

        .link-excluir-nota , .link-editar-nota {
            display: inline-block;
            height: 40px; 
            line-height: 40px; 
            background-color: whitesmoke; 
            text-align: center; 
            padding: 0 10px;
            color:black;
            border-radius:5px;
            text-decoration: none;
        }

    </style>
</head>
<body>
    <header>
        <h2>Meu app de notas - {{request.user.get_full_name}}</h2>
    </header>
    <main>
        {% block content %}{% endblock content %}
    </main>

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <!-- Popper.js -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

notas/templates/notas/nota_delete_view.html
{% extends "base.html" %}

{% block content %}
<div class="card-notas">
    <div>
        <h4>Excluir Nota</h4>
    </div>
    <div class="card-nota">
        <form action="{% url 'notas:delete_nota' nota.pk %}" method="post">
            {% csrf_token %}
            <div>
                Tem certeza que deseja excluir a nota {{nota.titulo}}?
            </div>
            <a type="button" href="{% url 'notas:listar_notas_user' %}" class="btn btn-secondary" data-dismiss="modal">Fechar</a>
            <button type="submit" class="btn btn-danger">Excluir</button>
        </form>
    </div>   
</div>
{% endblock content %}

notas/templates/notas/nota_update_view.html
{% extends "base.html" %}


{% block content %}
<div class="card-notas">
    <div>
        <h4>Editar Nota criada em {{nota.data_criacao}}</h4>
    </div>
    <div class="card-nota">
        <form action="{% url 'notas:update_nota' nota.pk %}" method="post">
            {% csrf_token %}
            <div>
                {{form.titulo.label}}
                <div>
                    {{form.titulo}}
                </div>
            </div>
            <div>
                {{form.conteudo.label}}
                <div>
                    {{form.conteudo}}
                </div>
            </div>
            <a type="button" href="{% url 'notas:listar_notas_user' %}" class="btn btn-secondary" data-dismiss="modal">Fechar</a>
            <button type="submit" class="btn btn-info">Salvar</button>
        </form>
    </div>   
</div>
{% endblock content %}

notas/templates/notas/notas_list_view.html
{% extends "base.html" %}

{% block content %}
  <!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Criar Nota</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form action="{% url 'notas:create_nota' %}" method="post">
            {% csrf_token %}
            <div class="modal-body">
                <div>
                    {{form.titulo.label}}
                    <div>
                        {{form.titulo}}
                    </div>
                </div>
                <div>
                    {{form.conteudo.label}}
                    <div>
                        {{form.conteudo}}
                    </div>
                </div>
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
            <button type="submit" class="btn btn-info">Salvar</button>
            </div>
        </form>
      </div>
    </div>
</div>
<div class="card-notas">
    <div>
        <a class="link-add-nota" data-toggle="modal" data-target="#exampleModal" href="">Adicionar Nota</a>
    </div>
    {% for nota in notas %}
        <div class="card-nota">
            <div class="row">
                <div class="col-md-9">
                    <h3>{{nota.titulo}}</h3> 
                    <span>{{nota.data_criacao}}</span>
                    <p>
                        {{nota.conteudo}}
                    </p>
                </div>
                <div class="col-md-3">
                    <a class="link-excluir-nota" href="{% url 'notas:delete_nota' nota.pk %}">
                        <i class="bi bi-trash"></i>
                    </a>
                    <a class="link-editar-nota" href="{% url 'notas:update_nota' nota.pk %}">
                        <i class="bi bi-pencil-square"></i>
                    </a>
                </div>
            </div>
        </div>   
    {% endfor %}
</div>

{% endblock content %}